# Generated by Django 2.2.6 on 2019-12-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191126_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='langualge',
            new_name='language',
        ),
    ]
